In [62]:
# Open and print the first few lines of the .dat file to understand its structure
with open('subject105.dat', 'r') as file:
    for _ in range(5):
        print(file.readline())

5.7 0 NaN 34 2.22755 9.65418 2.38862 2.31968 9.60752 2.58278 0.0162711 -0.0364337 -0.159489 -35.3864 -66.5838 18.621 1 0 0 0 35.625 1.45391 5.87561 -7.88825 1.19502 5.89807 -7.82306 -0.179294 -0.183116 0.154623 -12.7692 -33.8073 18.707 1 0 0 0 33.5 8.97893 -3.11115 -2.68324 9.0945 -3.01117 -2.37605 -0.017907 0.00933956 0.050097 -32.7091 31.4772 44.2318 0.255373 0.783075 0.0846021 0.560732

5.71 0 NaN 34 2.3755 9.57647 2.31412 2.45657 9.62177 2.71852 -0.103958 0.00255616 -0.124706 -35.8832 -66.9292 19.149 1 0 0 0 35.625 1.5697 5.98847 -7.8478 1.28692 5.97306 -7.62693 -0.159629 -0.127159 0.147688 -13.1666 -33.5351 19.1257 1 0 0 0 33.5 9.16496 -3.11201 -2.71992 9.06418 -3.07175 -2.43623 -0.0700909 0.00231184 0.0538325 -33.0782 30.9814 44.5148 0.251163 0.785583 0.0763192 0.560314

5.72 0 NaN 34 2.94208 9.53415 2.32275 2.78876 9.64961 2.76342 -0.0494598 0.0776451 -0.0455306 -34.7545 -67.3621 18.6245 1 0 0 0 35.625 1.52482 6.02469 -8.08106 1.39231 6.00303 -7.64259 -0.171019 -0.0735347 0.132653 -12.8944 -34.1897 18.8493 0.228238 -0.474889 0.814685 0.242231 33.5 9.00905 -3.0332 -2.95354 9.01897 -3.14743 -2.46602 -0.0844675 0.0342492 0.030462 -32.5619 30.6982 44.5169 0.250643 0.786419 0.0720376 0.559941

5.73 0 NaN 34 3.47541 9.75837 2.40696 3.3308 9.66073 2.68734 0.0122 0.138072 -0.0168711 -34.5069 -67.3752 18.7553 1 0 0 0 35.625 1.43944 6.02286 -8.39237 1.33117 6.03363 -7.8386 -0.165247 -0.133399 0.133739 -12.8979 -34.577 19.4155 0.2232 -0.475113 0.816146 0.241569 33.5 9.12364 -3.22471 -2.83541 9.01885 -3.14746 -2.49629 -0.0307893 0.0586149 0.0552517 -32.8212 30.969 44.6575 0.250917 0.786967 0.0710129 0.559179

5.74 0 NaN 34 3.54617 9.83232 2.25382 3.67642 9.71848 2.50565 0.0516294 0.154942 -0.00661997 -35.1327 -66.7217 18.2276 1 0 0 0 35.625 1.24887 6.02345 -8.39582 1.19473 6.06441 -8.04926 -0.175486 -0.135239 0.141257 -12.6348 -34.3282 18.8519 0.218865 -0.475258 0.817139 0.241893 33.5 9.19889 -3.14925 -2.83511 9.03428 -3.23808 -2.39013 -0.0200625 0.0209025 0.0596527 -33.1869 30.0856 44.5154 0.249631 0.786602 0.0668607 0.560777

In [64]:
import pandas as pd

# Replace 'delimiter_here' with the actual delimiter, e.g., '\t' for tab, ',' for comma, etc.
df = pd.read_csv('subject105.dat', delimiter='delimiter_here')

# Save to CSV
df.to_csv('subject105.csv', index=False)

C:\Users\Gjert\AppData\Local\Temp\ipykernel_37808\2135828022.py:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df = pd.read_csv('subject105.dat', delimiter='delimiter_here')

In [65]:
# Load the CSV file and print the first few rows to verify
df = pd.read_csv('subject105.csv')
print(df.head())

  5.7 0 NaN 34 2.22755 9.65418 2.38862 2.31968 9.60752 2.58278 0.0162711 -0.0364337 -0.159489 -35.3864 -66.5838 18.621 1 0 0 0 35.625 1.45391 5.87561 -7.88825 1.19502 5.89807 -7.82306 -0.179294 -0.183116 0.154623 -12.7692 -33.8073 18.707 1 0 0 0 33.5 8.97893 -3.11115 -2.68324 9.0945 -3.01117 -2.37605 -0.017907 0.00933956 0.050097 -32.7091 31.4772 44.2318 0.255373 0.783075 0.0846021 0.560732
0  5.71 0 NaN 34 2.3755 9.57647 2.31412 2.45657 9...
1  5.72 0 NaN 34 2.94208 9.53415 2.32275 2.78876 ...
2  5.73 0 NaN 34 3.47541 9.75837 2.40696 3.3308 9...
3  5.74 0 NaN 34 3.54617 9.83232 2.25382 3.67642 ...
4  5.75 0 NaN 34 4.03289 9.56229 2.18505 3.91692 ...

In [66]:
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
from IPython.display import display
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.metrics import confusion_matrix,accuracy_score,log_loss
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import OneHotEncoder
from keras.models import Sequential
from keras.models import Model
from keras.layers import Dense, Input, LSTM, Dropout

In [67]:
def load_activity_map():
    map = {}
    map[0] = 'transient'
    map[1] = 'lying'
    map[2] = 'sitting'
    map[3] = 'standing'
    map[4] = 'walking'
    map[5] = 'running'
    map[6] = 'cycling'
    map[7] = 'Nordic_walking'
    map[9] = 'watching_TV'
    map[10] = 'computer_work'
    map[11] = 'car driving'
    map[12] = 'ascending_stairs'
    map[13] = 'descending_stairs'
    map[16] = 'vacuum_cleaning'
    map[17] = 'ironing'
    map[18] = 'folding_laundry'
    map[19] = 'house_cleaning'
    map[20] = 'playing_soccer'
    map[24] = 'rope_jumping'
    return map

In [68]:
def generate_three_IMU(name):
    x = name +'_x'
    y = name +'_y'
    z = name +'_z'
    return [x,y,z]

def generate_four_IMU(name):
    x = name +'_x'
    y = name +'_y'
    z = name +'_z'
    w = name +'_w'
    return [x,y,z,w]

def generate_cols_IMU(name):
    # temp
    temp = name+'_temperature'
    output = [temp]
    # acceleration 16
    acceleration16 = name+'_3D_acceleration_16'
    acceleration16 = generate_three_IMU(acceleration16)
    output.extend(acceleration16)
    # acceleration 6
    acceleration6 = name+'_3D_acceleration_6'
    acceleration6 = generate_three_IMU(acceleration6)
    output.extend(acceleration6)
    # gyroscope
    gyroscope = name+'_3D_gyroscope'
    gyroscope = generate_three_IMU(gyroscope)
    output.extend(gyroscope)
    # magnometer
    magnometer = name+'_3D_magnetometer'
    magnometer = generate_three_IMU(magnometer)
    output.extend(magnometer)
    # oreintation
    oreintation = name+'_4D_orientation'
    oreintation = generate_four_IMU(oreintation)
    output.extend(oreintation)
    return output

def load_IMU():
    output = ['time_stamp','activity_id', 'heart_rate']
    hand = 'hand'
    hand = generate_cols_IMU(hand)
    output.extend(hand)
    chest = 'chest'
    chest = generate_cols_IMU(chest)
    output.extend(chest)
    ankle = 'ankle'
    ankle = generate_cols_IMU(ankle)
    output.extend(ankle)
    return output

In [69]:

def load_subjects(root='subject'):
    output = pd.DataFrame()
    cols = load_IMU()
    
    dataframes = []  # List to store individual dataframes
    for i in range(101, 110):
        path = root + str(i) + '.dat'
        subject = pd.read_table(path, header=None, sep='\s+')
        subject.columns = cols
        subject['id'] = i
        dataframes.append(subject)  # Append the dataframe to the list
    
    output = pd.concat(dataframes, ignore_index=True)  # Concatenate all dataframes
    output.reset_index(drop=True, inplace=True)
    return output

data = load_subjects()

In [70]:
data

,time_stamp,activity_id,heart_rate,hand_temperature,hand_3D_acceleration_16_x,hand_3D_acceleration_16_y,hand_3D_acceleration_16_z,hand_3D_acceleration_6_x,hand_3D_acceleration_6_y,hand_3D_acceleration_6_z,...,ankle_3D_gyroscope_y,ankle_3D_gyroscope_z,ankle_3D_magnetometer_x,ankle_3D_magnetometer_y,ankle_3D_magnetometer_z,ankle_4D_orientation_x,ankle_4D_orientation_y,ankle_4D_orientation_z,ankle_4D_orientation_w,id
0,8.38,0,104.0,30.0000,2.37223,8.60074,3.51048,2.43954,8.76165,3.35465,...,0.009250,-0.017580,-61.1888,-38.95990,-58.143800,1.000000,0.000000,0.000000,0.000000,101
1,8.39,0,NaN,30.0000,2.18837,8.56560,3.66179,2.39494,8.55081,3.64207,...,-0.004638,0.000368,-59.8479,-38.89190,-58.525300,1.000000,0.000000,0.000000,0.000000,101
2,8.40,0,NaN,30.0000,2.37357,8.60107,3.54898,2.30514,8.53644,3.73280,...,0.000148,0.022495,-60.7361,-39.41380,-58.399900,1.000000,0.000000,0.000000,0.000000,101
3,8.41,0,NaN,30.0000,2.07473,8.52853,3.66021,2.33528,8.53622,3.73277,...,-0.020301,0.011275,-60.4091,-38.76350,-58.395600,1.000000,0.000000,0.000000,0.000000,101
4,8.42,0,NaN,30.0000,2.22936,8.83122,3.70000,2.23055,8.59741,3.76295,...,-0.014303,-0.002823,-61.5199,-39.38790,-58.269400,1.000000,0.000000,0.000000,0.000000,101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2872528,100.19,0,NaN,25.1875,-4.71493,10.22250,4.66893,-5.04654,9.94944,4.50736,...,-0.062676,-0.127084,-46.5153,3.58240,-0.035995,0.598531,0.033615,0.799791,-0.031075,109
2872529,100.20,0,NaN,25.1875,-4.95932,10.37130,4.12594,-4.96890,10.29620,4.43102,...,-0.027006,-0.089808,-45.7474,3.54453,0.108583,0.598428,0.033012,0.799933,-0.030018,109
2872530,100.21,0,NaN,25.1875,-4.93997,9.83615,3.70468,-5.04613,10.35690,4.14405,...,-0.038024,-0.064709,-46.3997,4.22078,0.105504,0.598233,0.033172,0.800095,-0.029416,109
2872531,100.22,0,NaN,25.1875,-4.64941,9.11129,3.51904,-5.06854,9.75268,3.87359,...,-0.025796,-0.064357,-46.5282,4.48593,0.530240,0.598116,0.033427,0.800180,-0.029208,109
2872532,100.23,0,161.0,25.1875,-4.09726,8.15642,3.29961,-4.73244,8.82870,3.54305,...,0.011866,-0.042858,-46.2704,4.21475,0.247798,0.598119,0.033685,0.800188,-0.028602,109

In [71]:
# Saving the DataFrame to a CSV file
data.to_csv('PAMAP2ALL.csv', index=False)

In [72]:
df = pd.read_csv('PAMAP2ALL.csv')

In [73]:
print(df.columns)

Index(['time_stamp', 'activity_id', 'heart_rate', 'hand_temperature',
       'hand_3D_acceleration_16_x', 'hand_3D_acceleration_16_y',
       'hand_3D_acceleration_16_z', 'hand_3D_acceleration_6_x',
       'hand_3D_acceleration_6_y', 'hand_3D_acceleration_6_z',
       'hand_3D_gyroscope_x', 'hand_3D_gyroscope_y', 'hand_3D_gyroscope_z',
       'hand_3D_magnetometer_x', 'hand_3D_magnetometer_y',
       'hand_3D_magnetometer_z', 'hand_4D_orientation_x',
       'hand_4D_orientation_y', 'hand_4D_orientation_z',
       'hand_4D_orientation_w', 'chest_temperature',
       'chest_3D_acceleration_16_x', 'chest_3D_acceleration_16_y',
       'chest_3D_acceleration_16_z', 'chest_3D_acceleration_6_x',
       'chest_3D_acceleration_6_y', 'chest_3D_acceleration_6_z',
       'chest_3D_gyroscope_x', 'chest_3D_gyroscope_y', 'chest_3D_gyroscope_z',
       'chest_3D_magnetometer_x', 'chest_3D_magnetometer_y',
       'chest_3D_magnetometer_z', 'chest_4D_orientation_x',
       'chest_4D_orientation_y', 'chest_4D_orientation_z',
       'chest_4D_orientation_w', 'ankle_temperature',
       'ankle_3D_acceleration_16_x', 'ankle_3D_acceleration_16_y',
       'ankle_3D_acceleration_16_z', 'ankle_3D_acceleration_6_x',
       'ankle_3D_acceleration_6_y', 'ankle_3D_acceleration_6_z',
       'ankle_3D_gyroscope_x', 'ankle_3D_gyroscope_y', 'ankle_3D_gyroscope_z',
       'ankle_3D_magnetometer_x', 'ankle_3D_magnetometer_y',
       'ankle_3D_magnetometer_z', 'ankle_4D_orientation_x',
       'ankle_4D_orientation_y', 'ankle_4D_orientation_z',
       'ankle_4D_orientation_w', 'id'],
      dtype='object')

In [74]:
# List of columns to be dropped
columns_to_drop = [
    'hand_3D_gyroscope_x', 'hand_3D_gyroscope_y', 'hand_3D_gyroscope_z','heart_rate','hand_3D_magnetometer_x','hand_temperature',
    'hand_3D_magnetometer_x', 'hand_3D_magnetometer_y', 'hand_3D_magnetometer_z', 
    'hand_4D_orientation_x', 'hand_4D_orientation_y', 'hand_4D_orientation_z', 'hand_4D_orientation_w',
    'chest_temperature', 'chest_3D_acceleration_16_x', 'chest_3D_acceleration_16_y', 'chest_3D_acceleration_16_z', 
    'chest_3D_acceleration_6_x', 'chest_3D_acceleration_6_y', 'chest_3D_acceleration_6_z', 
    'chest_3D_gyroscope_x', 'chest_3D_gyroscope_y', 'chest_3D_gyroscope_z', 
    'chest_3D_magnetometer_x', 'chest_3D_magnetometer_y', 'chest_3D_magnetometer_z', 
    'chest_4D_orientation_x', 'chest_4D_orientation_y', 'chest_4D_orientation_z', 'chest_4D_orientation_w', 
    'ankle_temperature', 'ankle_3D_acceleration_16_x', 'ankle_3D_acceleration_16_y', 'ankle_3D_acceleration_16_z', 
    'ankle_3D_acceleration_6_x', 'ankle_3D_acceleration_6_y', 'ankle_3D_acceleration_6_z', 
    'ankle_3D_gyroscope_x', 'ankle_3D_gyroscope_y', 'ankle_3D_gyroscope_z', 
    'ankle_3D_magnetometer_x', 'ankle_3D_magnetometer_y', 'ankle_3D_magnetometer_z', 
    'ankle_4D_orientation_x', 'ankle_4D_orientation_y', 'ankle_4D_orientation_z', 'ankle_4D_orientation_w'
]

# Drop the specified columns
df_cleaned = df.drop(columns=columns_to_drop, errors='ignore')  # errors='ignore' will ignore any errors if a column is not found

In [80]:
# Save the cleaned DataFrame to a new CSV file
df_cleaned.to_csv('PAMAP2_Cleaned.csv', index=False)

In [81]:
# Load the new CSV to verify
df_new = pd.read_csv('PAMAP2_Cleaned.csv')
print(df_new.head())  # Display the first few rows to check the remaining columns

   time_stamp  activity_id  hand_3D_acceleration_16_x  \
0        8.38            0                    2.37223
1        8.39            0                    2.18837
2        8.40            0                    2.37357
3        8.41            0                    2.07473
4        8.42            0                    2.22936

   hand_3D_acceleration_16_y  hand_3D_acceleration_16_z  \
0                    8.60074                    3.51048
1                    8.56560                    3.66179
2                    8.60107                    3.54898
3                    8.52853                    3.66021
4                    8.83122                    3.70000

   hand_3D_acceleration_6_x  hand_3D_acceleration_6_y  \
0                   2.43954                   8.76165
1                   2.39494                   8.55081
2                   2.30514                   8.53644
3                   2.33528                   8.53622
4                   2.23055                   8.59741

   hand_3D_acceleration_6_z   id
0                   3.35465  101
1                   3.64207  101
2                   3.73280  101
3                   3.73277  101
4                   3.76295  101

In [82]:
print(df_new.columns)

Index(['time_stamp', 'activity_id', 'hand_3D_acceleration_16_x',
       'hand_3D_acceleration_16_y', 'hand_3D_acceleration_16_z',
       'hand_3D_acceleration_6_x', 'hand_3D_acceleration_6_y',
       'hand_3D_acceleration_6_z', 'id'],
      dtype='object')

In [83]:
activity_map = {
    0: 'transient',
    1: 'lying',
    2: 'sitting',
    3: 'standing',
    4: 'walking',
    5: 'running',
    6: 'cycling',
    7: 'Nordic_walking',
    9: 'watching_TV',
    10: 'computer_work',
    11: 'car driving',
    12: 'ascending_stairs',
    13: 'descending_stairs',
    16: 'vacuum_cleaning',
    17: 'ironing',
    18: 'folding_laundry',
    19: 'house_cleaning',
    20: 'playing_soccer',
    24: 'rope_jumping'
}
df_new['activity_id'] = df_new['activity_id'].map(activity_map)

print(df_new[['activity_id']].head(10))  # Print the first 10 rows of the 'activity_id' column

  activity_id
0   transient
1   transient
2   transient
3   transient
4   transient
5   transient
6   transient
7   transient
8   transient
9   transient

In [94]:
import numpy as np

# Define activities to remove
activities_to_drop = ['playing_soccer', 'computer_work', 'car driving', 'running', 'transient']

# Filter out unwanted activities and NaN values
df_filtered = df_new[~df_new['activity_id'].isin(activities_to_drop)]  # Drop specified activities
df_filtered = df_filtered.dropna(subset=['activity_id'])  # Remove NaN values

# Print unique activities in the filtered dataset
print("Unique activities in the filtered dataset:", df_filtered['activity_id'].unique())

Unique activities in the filtered dataset: ['lying' 'sitting' 'standing' 'ironing' 'vacuum_cleaning'
 'ascending_stairs' 'descending_stairs' 'walking' 'Nordic_walking'
 'cycling' 'rope_jumping']

In [100]:
# Define activity replacements
activity_replacements = {
    'vacuum_cleaning': 'standing_household_chores',
    'ironing': 'standing_household_chores',
    'folding_laundry': 'standing_household_chores',
    'house_cleaning': 'standing_household_chores',
    'watching_TV': 'sitting',
    'rope_jumping': 'jumping'  # Rename 'rope_jumping' to 'jumping'
}

# Apply replacements
df_filtered['activity_id'] = df_filtered['activity_id'].replace(activity_replacements)

# Print unique activities to verify changes
print("Unique activities after merging & renaming:", df_filtered['activity_id'].unique())

Unique activities after merging & renaming: ['lying' 'sitting' 'standing' 'standing_household_chores'
 'ascending_stairs' 'descending_stairs' 'walking' 'Nordic_walking'
 'cycling' 'jumping']

In [104]:
unique_activities = df_filtered['activity_id'].unique()

# Print all unique activity IDs
print(unique_activities)

['lying' 'sitting' 'standing' 'standing_household_chores'
 'ascending_stairs' 'descending_stairs' 'walking' 'Nordic_walking'
 'cycling' 'jumping']

In [108]:
# Rename the column 'activity_id' to 'label'
df_filtered = df_filtered.rename(columns={'activity_id': 'label'})

# Print unique labels to verify
unique_activities = df_filtered['label'].unique()
print("Unique activities after renaming:", unique_activities)

Unique activities after renaming: ['lying' 'sitting' 'standing' 'standing_household_chores'
 'ascending_stairs' 'descending_stairs' 'walking' 'Nordic_walking'
 'cycling' 'jumping']

In [110]:
df_filtered.to_csv('PAMAP2_Cleaned.csv', index=False)